# Generated by Django 5.1.2 on 2025-07-09 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название помещения', max_length=150, unique=True, verbose_name='Название помещения')),
                ('description', models.TextField(blank=True, help_text='Описание помещения', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название причины отмены брони', max_length=255, verbose_name='Причина отмены')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли эту причину в списке', verbose_name='Активна')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения в списке (меньше = выше)', verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Причина отмены',
                'verbose_name_plural': 'Причины отмены',
                'db_table': 'cancellation_reasons',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название группы', max_length=100, unique=True, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа клиента',
                'verbose_name_plural': 'Группы клиентов',
                'db_table': 'client_groups',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название типа оплаты', max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание типа оплаты', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Типы оплаты',
                'db_table': 'payment_types',
            },
        ),
        migrations.CreateModel(
            name='ReservationStatusType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название статуса', max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание статуса', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип статуса бронирования',
                'verbose_name_plural': 'Типы статусов бронирования',
                'db_table': 'reservation_status_types',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Наименование сценария', max_length=100, unique=True, verbose_name='Наименование сценария')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
                'db_table': 'scenarios',
            },
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Наименование группы услуг', max_length=100, unique=True, verbose_name='Наименование группы услуг')),
                ('active', models.BooleanField(default=True, help_text='Активность группы услуг (включена или нет)', verbose_name='Активность группы услуг')),
            ],
            options={
                'verbose_name': 'Группа услуг',
                'verbose_name_plural': 'Группы услуг',
                'db_table': 'service_groups',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ФИО клиента', max_length=150, verbose_name='ФИО клиента')),
                ('comment', models.TextField(blank=True, help_text='Комментарий к клиенту', null=True, verbose_name='Комментарий к клиенту')),
                ('phone', models.CharField(help_text='Телефон клиента', max_length=150, unique=True, verbose_name='Телефон клиента')),
                ('email', models.EmailField(blank=True, help_text='Email клиента', max_length=150, null=True, verbose_name='Email клиента')),
                ('groups', models.ManyToManyField(blank=True, help_text='Группы, в которые входит клиент', related_name='clients', to='booking.clientgroup', verbose_name='Группы клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Оценка выставленная клиенту', verbose_name='Оценка клиента')),
                ('comment', models.TextField(blank=True, help_text='Комментарий к оценке', null=True, verbose_name='Комментарий к оценке')),
                ('client', models.ForeignKey(help_text='ID клиента', on_delete=django.db.models.deletion.PROTECT, to='booking.client')),
            ],
            options={
                'verbose_name': 'Оценка клиента',
                'verbose_name_plural': 'Оценки клиентов',
                'db_table': 'client_ratings',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetimestart', models.DateTimeField(help_text='Дата и время начала брони', verbose_name='Datetime начала')),
                ('datetimeend', models.DateTimeField(help_text='Дата и время окончания брони', verbose_name='Datetime конца')),
                ('comment', models.TextField(help_text='Комментарий к брони', null=True, verbose_name='Комментарий')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Общая стоимость брони', max_digits=10, null=True, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания брони', verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления брони', verbose_name='Обновлена')),
                ('cancellation_reason', models.ForeignKey(blank=True, help_text='Причина отмены брони', null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.cancellationreason', verbose_name='Причина отмены')),
                ('client', models.ForeignKey(help_text='ID клиента, закрепленного за бронью', on_delete=django.db.models.deletion.PROTECT, to='booking.client', verbose_name='ID клиента')),
                ('client_group', models.ForeignKey(help_text='ID группы (коллектива) клиента, закрепленного за бронью, если групповое бронирование', null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.clientgroup', verbose_name='ID группы клиента')),
                ('status', models.ForeignKey(help_text='Статус брони', null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.reservationstatustype', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма платежа', max_digits=10, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания платежа', verbose_name='Создан')),
                ('comment', models.TextField(blank=True, help_text='Комментарий к платежу', null=True, verbose_name='Комментарий')),
                ('payment_type', models.ForeignKey(help_text='Тип платежа', on_delete=django.db.models.deletion.PROTECT, to='booking.paymenttype', verbose_name='Тип платежа')),
                ('reservation', models.ForeignKey(help_text='Бронь, к которой относится платёж', on_delete=django.db.models.deletion.PROTECT, to='booking.reservation', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Наименование комнаты', max_length=150, unique=True, verbose_name='Наименование комнаты')),
                ('hourstart', models.TimeField(help_text='Время начала работы комнаты', verbose_name='Начало работы')),
                ('hourend', models.TimeField(help_text='Время окончания работы комнаты', verbose_name='Конец работы')),
                ('area', models.ForeignKey(blank=True, help_text='ID помещения, к которому относится комната', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.area', verbose_name='Помещение')),
                ('scenario', models.ManyToManyField(help_text='Типы бронирования (сценарии), доступные для комнаты', related_name='rooms', to='booking.scenario', verbose_name='Типы бронирования (сценарии)')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'db_table': 'rooms',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(help_text='ID помещения, которое забронировано', on_delete=django.db.models.deletion.PROTECT, to='booking.room', verbose_name='ID помещения'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='scenario',
            field=models.ForeignKey(help_text='ID сценария', on_delete=django.db.models.deletion.PROTECT, to='booking.scenario', verbose_name='ID сценария'),
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_before', models.PositiveIntegerField(default=2, help_text='За сколько часов до начала брони можно отменить без штрафа', verbose_name='Часов до начала')),
                ('scenario', models.OneToOneField(help_text='Сценарий, к которому применяется политика отмены', on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_policy', to='booking.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Правило отмены бронирования',
                'verbose_name_plural': 'Правила отмены бронирования',
                'db_table': 'cancellation_policies',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Наименование услуги', max_length=100, unique=True, verbose_name='Наименование услуги')),
                ('active', models.BooleanField(default=True, help_text='Активность услуги (включена или нет)', verbose_name='Активность услуги')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Стоимость услуги', max_digits=10, verbose_name='Стоимость')),
                ('scenario', models.ManyToManyField(help_text='Сценарии, доступные для услуги', related_name='services', to='booking.scenario', verbose_name='Сценарии')),
                ('group', models.ForeignKey(help_text='Группа услуг', on_delete=django.db.models.deletion.PROTECT, to='booking.servicegroup', verbose_name='Группа услуг')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'services',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='service',
            field=models.ManyToManyField(help_text='Услуги доступные для комнаты', related_name='services', to='booking.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Услуги, включенные в бронь', related_name='reservations', to='booking.service', verbose_name='Услуги'),
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ФИО специалиста', max_length=100, unique=True, verbose_name='ФИО специалиста')),
                ('active', models.BooleanField(default=True, help_text='Активность специалиста (работает или нет)', verbose_name='Активность специалиста')),
                ('client', models.ForeignKey(help_text='ID клиента (для тех случаев, когда специалист выступает в роли клиента для бронирования)', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.client', verbose_name='ID клиента')),
                ('scenario', models.ManyToManyField(help_text='Типы бронирования доступные для специалиста', related_name='scenarios', to='booking.scenario', verbose_name='Типы бронирования')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
                'db_table': 'specialists',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='specialist',
            field=models.ForeignKey(help_text='ID специалиста, закрепленного за бронью', null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.specialist', verbose_name='ID специалиста'),
        ),
        migrations.CreateModel(
            name='SpecialistColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(help_text='HEX код цвета (например, #FF5733)', max_length=7, verbose_name='Основной цвет')),
                ('secondary_color', models.CharField(help_text='HEX код цвета для градиента', max_length=7, verbose_name='Дополнительный цвет')),
                ('specialist', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='color_scheme', to='booking.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Цветовая схема специалиста',
                'verbose_name_plural': 'Цветовые схемы специалистов',
                'db_table': 'specialist_colors',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(help_text='Баланс тарифных единиц', verbose_name='Баланс тарифных единиц')),
                ('client', models.ForeignKey(help_text='ID клиента', on_delete=django.db.models.deletion.PROTECT, to='booking.client', verbose_name='ID клиента')),
                ('scenario', models.ForeignKey(help_text='ID сценария', on_delete=django.db.models.deletion.PROTECT, to='booking.scenario', verbose_name='ID сценария')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='TariffUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_reservation_time', models.TimeField(help_text='Минимальное время бронирования (размер тарифной единицы)', verbose_name='Минимальное время бронирования')),
                ('tariff_unit_cost', models.DecimalField(decimal_places=2, help_text='Стоимость тарифной единицы', max_digits=10, verbose_name='Стоимость тарифной единицы')),
                ('scenario', models.ForeignKey(help_text='ID сценария', on_delete=django.db.models.deletion.PROTECT, to='booking.scenario', verbose_name='ID сценария')),
            ],
            options={
                'verbose_name': 'Тарифная единица',
                'verbose_name_plural': 'Тарифные единицы',
                'db_table': 'tariff_units',
                'unique_together': {('scenario',)},
            },
        ),
    ]
