# Generated by Django 5.1.2 on 2024-10-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iduser', models.IntegerField()),
                ('hours', models.CharField(max_length=50)),
                ('hoursleft', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('moneyleft', models.CharField(max_length=50)),
                ('validity', models.CharField(max_length=50)),
                ('datesale', models.CharField(max_length=50)),
                ('datefirstbron', models.CharField(max_length=50)),
                ('dateexpired', models.CharField(max_length=50)),
                ('oblast', models.IntegerField()),
                ('probnoe', models.IntegerField()),
                ('hide', models.IntegerField()),
                ('idbron', models.IntegerField()),
            ],
            options={
                'db_table': 'abon',
            },
        ),
    ]
