# Generated by Django 5.1.2 on 2024-10-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iditem', models.IntegerField()),
                ('date', models.CharField(max_length=150)),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'active_client',
            },
        ),
    ]
