# Generated by Django 5.1.2 on 2025-07-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='scenario',
        ),
        migrations.AddField(
            model_name='area',
            name='scenario',
            field=models.ManyToManyField(help_text='Типы бронирования (сценарии), доступные для помещения', related_name='areas', to='booking.scenario', verbose_name='Типы бронирования (сценарии)'),
        ),
    ]
