# Generated by Django 5.1.2 on 2025-07-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_room_scenario_area_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='scenario',
            field=models.ManyToManyField(help_text='Типы бронирования (сценарии), доступные для комнаты', related_name='rooms', to='booking.scenario', verbose_name='Типы бронирования (сценарии)'),
        ),
    ]
