# Generated by Django 5.1.2 on 2024-10-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_activeclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iduser', models.IntegerField()),
                ('hash', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'authtable',
            },
        ),
    ]
