# Generated by Django 5.1.2 on 2024-11-28 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_client_id_alter_clientgroup_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(help_text='HEX код цвета (например, #FF5733)', max_length=7, verbose_name='Основной цвет')),
                ('secondary_color', models.CharField(help_text='HEX код цвета для градиента', max_length=7, verbose_name='Дополнительный цвет')),
                ('specialist', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='color_scheme', to='booking.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Цветовая схема специалиста',
                'verbose_name_plural': 'Цветовые схемы специалистов',
            },
        ),
    ]
