# Generated by Django 5.1.2 on 2024-10-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_authtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('mon', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('timestart', models.CharField(max_length=50)),
                ('timeend', models.CharField(max_length=50)),
                ('idprepod', models.IntegerField()),
                ('iduser', models.IntegerField()),
                ('idroom', models.IntegerField()),
                ('period', models.CharField(max_length=50)),
                ('hide', models.IntegerField()),
                ('status', models.IntegerField()),
                ('pay', models.CharField(max_length=50)),
                ('numbron', models.IntegerField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'bron',
            },
        ),
    ]
