# Generated by Django 5.1.2 on 2024-11-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_specialistcolor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='specialistcolor',
            table='specialist_colors',
        ),
    ]
