# Generated by Django 5.1.2 on 2024-10-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bron'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoredBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idroom', models.IntegerField()),
                ('weekday', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('min', models.IntegerField()),
            ],
            options={
                'db_table': 'coloredblock',
            },
        ),
        migrations.CreateModel(
            name='ConnectUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iduser1', models.IntegerField()),
                ('iduser2', models.IntegerField()),
            ],
            options={
                'db_table': 'connect_user',
            },
        ),
    ]
