# Generated by Django 5.1.2 on 2025-07-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_add_reservation_status_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='scenario',
            field=models.ManyToManyField(blank=True, help_text='Типы бронирования (сценарии), доступные для комнаты', related_name='rooms', to='booking.scenario', verbose_name='Типы бронирования (сценарии)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='service',
            field=models.ManyToManyField(blank=True, help_text='Услуги доступные для комнаты', related_name='services', to='booking.service', verbose_name='Услуги'),
        ),
    ]
