# Generated by Django 5.1.2 on 2024-11-28 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_specialistcolor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_before', models.PositiveIntegerField(default=2, help_text='За сколько часов до начала брони можно отменить без штрафа', verbose_name='Часов до начала')),
                ('reservation_type', models.OneToOneField(help_text='Тип бронирования, к которому применяется политика отмены', on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_policy', to='booking.reservationtype', verbose_name='Тип бронирования')),
            ],
            options={
                'verbose_name': 'Правило отмены бронирования',
                'verbose_name_plural': 'Правила отмены бронирования',
                'db_table': 'cancellation_policies',
            },
        ),
    ]
