# Generated by Django 5.1.2 on 2024-12-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_cancellationpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Общая стоимость брони', max_digits=10, null=True, verbose_name='Стоимость'),
        ),
    ]
