# Generated by Django 5.1.2 on 2025-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_room_scenario_alter_room_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='scenario',
            field=models.ManyToManyField(blank=True, help_text='Сценарии, доступные для услуги', related_name='services', to='booking.scenario', verbose_name='Сценарии'),
        ),
    ]
