# Generated by Django 5.1.2 on 2024-10-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_coloredblock_connectuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruslugi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('prior', models.IntegerField()),
                ('hide', models.IntegerField()),
            ],
            options={
                'db_table': 'gruslugi',
            },
        ),
    ]
