# Generated by Django 5.1.2 on 2024-12-03 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_reservation_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название типа оплаты', max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание типа оплаты', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Типы оплаты',
                'db_table': 'payment_types',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма платежа', max_digits=10, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания платежа', verbose_name='Создан')),
                ('comment', models.TextField(blank=True, help_text='Комментарий к платежу', null=True, verbose_name='Комментарий')),
                ('reservation', models.ForeignKey(help_text='Бронь, к которой относится платёж', on_delete=django.db.models.deletion.PROTECT, to='booking.reservation', verbose_name='Бронь')),
                ('payment_type', models.ForeignKey(help_text='Тип платежа', on_delete=django.db.models.deletion.PROTECT, to='booking.paymenttype', verbose_name='Тип платежа')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payments',
            },
        ),
    ]
