# Generated by Django 5.1.2 on 2024-10-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_gruslugi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'log',
            },
        ),
    ]
