# Generated by Django 5.1.2 on 2025-07-16 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_service_scenario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Комната, к которой относится услуга', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(help_text='ID комнаты, которая забронирована', on_delete=django.db.models.deletion.PROTECT, to='booking.room', verbose_name='ID комнаты'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='scenario',
        ),
        migrations.AddField(
            model_name='service',
            name='scenario',
            field=models.ForeignKey(blank=True, help_text='Сценарий, доступный для услуги', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.scenario', verbose_name='Сценарий'),
        ),
    ]
