# Generated by Django 5.1.2 on 2024-12-04 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_paymenttype_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название причины отмены брони', max_length=255, verbose_name='Причина отмены')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли эту причину в списке', verbose_name='Активна')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения в списке (меньше = выше)', verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Причина отмены',
                'verbose_name_plural': 'Причины отмены',
                'db_table': 'cancellation_reasons',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.ForeignKey(blank=True, help_text='Причина отмены брони', null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.cancellationreason', verbose_name='Причина отмены'),
        ),
    ]
