# Generated by Django 5.1.2 on 2024-10-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerSmena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('iduser', models.IntegerField()),
                ('timestart', models.CharField(max_length=50)),
                ('timeend', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'managersmena',
            },
        ),
    ]
