# Generated by Django 5.1.2 on 2025-07-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_room_service_service_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationreason',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
