# Generated by Django 5.1.2 on 2025-07-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_cancellationreason_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='active',
            field=models.BooleanField(default=True, help_text='Активен ли сценарий', verbose_name='Активность'),
        ),
    ]
