# Generated by Django 5.1.2 on 2024-12-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_cancellationreason_reservation_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость услуги', max_digits=10, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='service',
            name='reservation_type',
            field=models.ManyToManyField(help_text='Типы бронирования доступные для услуги', related_name='services', to='booking.reservationtype', verbose_name='Типы бронирования'),
        ),
    ]
