# Generated by Django 5.1.2 on 2024-10-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_managersmena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oblast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameru', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'oblast',
            },
        ),
    ]
