# Generated by Django 5.1.2 on 2024-12-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_service_cost_alter_service_reservation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text='Email клиента', max_length=150, null=True, verbose_name='Email клиента'),
        ),
    ]
