# Generated by Django 5.1.2 on 2024-10-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_oblast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idbron', models.IntegerField()),
                ('typepay', models.CharField(max_length=50)),
                ('money', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=50)),
                ('opisanie', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('idoblast', models.IntegerField()),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
