# Generated by Django 5.1.2 on 2025-07-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_scenario_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(help_text='Название помещения', max_length=150, verbose_name='Название помещения'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Наименование комнаты', max_length=150, verbose_name='Наименование комнаты'),
        ),
    ]
