# Generated by Django 5.1.2 on 2025-01-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(help_text='Телефон клиента', max_length=150, verbose_name='Телефон клиента'),
        ),
    ]
