# Generated by Django 5.1.2 on 2024-10-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idbron', models.IntegerField()),
                ('idpaymenttype', models.IntegerField()),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'paymentdetail',
            },
        ),
    ]
