# Generated by Django 5.1.2 on 2025-07-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_area_name_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientgroup',
            name='name',
            field=models.CharField(help_text='Название группы', max_length=100, verbose_name='Название группы'),
        ),
    ]
