# Generated by Django 5.1.2 on 2024-10-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_paymentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameru', models.CharField(max_length=150)),
                ('hide', models.IntegerField()),
                ('prior', models.IntegerField()),
            ],
            options={
                'db_table': 'paymenttype',
            },
        ),
    ]
