# Generated by Django 5.1.2 on 2025-07-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_clientgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Наименование услуги', max_length=100, verbose_name='Наименование услуги'),
        ),
    ]
