# Generated by Django 5.1.2 on 2025-12-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата обновления платежа', verbose_name='Обновлён'),
        ),
    ]
