# Generated by Django 5.1.2 on 2024-10-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_paymenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('hourstart', models.IntegerField()),
                ('hourend', models.IntegerField()),
                ('period', models.IntegerField()),
                ('idoblast', models.IntegerField()),
                ('prior', models.IntegerField()),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
