# Generated by Django 5.1.2 on 2025-01-31 10:50

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Телефон клиента', max_length=128, region='BY', unique=True, verbose_name='Телефон клиента'),
        ),
    ]
