# Generated by Django 5.1.2 on 2024-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iduser', models.IntegerField()),
                ('salary', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'salary',
            },
        ),
    ]
