# Generated by Django 5.1.2 on 2025-12-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_payment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='canceled',
            field=models.BooleanField(default=False, help_text='Флаг отмены платежа (не участвует в расчётах)', verbose_name='Отменён'),
        ),
    ]
