# Generated by Django 5.1.2 on 2024-10-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('iduser', models.IntegerField()),
            ],
            options={
                'db_table': 'smena',
            },
        ),
    ]
