# Generated by Django 5.1.2 on 2024-10-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_smena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarifname', models.CharField(max_length=150)),
                ('idroom', models.IntegerField()),
                ('prior', models.IntegerField()),
            ],
            options={
                'db_table': 'tarif',
            },
        ),
    ]
