# Generated by Django 5.1.2 on 2025-12-08 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_direction_specialist_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='direction',
            field=models.ForeignKey(blank=True, help_text='Выбранное направление специалиста для этой брони', null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.direction', verbose_name='Направление специалиста'),
        ),
    ]
