# Generated by Django 5.1.2 on 2025-02-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_client_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationtype',
            options={'verbose_name': 'Тип бронирования (сценарий)', 'verbose_name_plural': 'Типы бронирования (сценарии)'},
        ),
        migrations.AlterField(
            model_name='reservationtype',
            name='name',
            field=models.CharField(help_text='Наименование типа бронирования (сценария)', max_length=100, unique=True, verbose_name='Наименование типа бронирования'),
        ),
    ]
