# Generated by Django 5.1.2 on 2025-12-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_reservation_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='work_time_end',
            field=models.TimeField(blank=True, help_text='Время окончания работы по сценарию', null=True, verbose_name='Окончание работы сценария'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='work_time_start',
            field=models.TimeField(blank=True, help_text='Время начала работы по сценарию', null=True, verbose_name='Начало работы сценария'),
        ),
    ]
