# Generated by Django 5.1.2 on 2024-10-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_tarif'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifSaveBron',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idbron', models.IntegerField()),
                ('idtarif', models.IntegerField()),
                ('skidka', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tarifsavebron',
            },
        ),
    ]
