# Generated by Django 5.1.2 on 2025-02-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_reservationtype_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tariffunit',
            unique_together={('reservation_type',)},
        ),
    ]
