# Generated by Django 5.1.2 on 2025-02-21 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_tariffunit_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Стоимость услуги', max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='service',
            name='group',
            field=models.ForeignKey(help_text='Группа услуг', on_delete=django.db.models.deletion.PROTECT, to='booking.servicegroup', verbose_name='Группа услуг'),
        ),
    ]
