# Generated by Django 5.1.2 on 2024-10-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_tarifsavebron'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idtarif', models.IntegerField()),
                ('day', models.IntegerField()),
                ('timefrom', models.CharField(max_length=50)),
                ('timeto', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tarifsetting',
            },
        ),
    ]
