# Generated by Django 5.1.2 on 2024-10-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_tarifsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=150)),
                ('datelogin', models.CharField(max_length=150)),
                ('timelogin', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'trytable',
            },
        ),
    ]
