# Generated by Django 5.1.2 on 2024-10-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_trytable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iduser', models.IntegerField()),
                ('image', models.CharField(max_length=50)),
                ('hide', models.IntegerField()),
            ],
            options={
                'db_table': 'userimage',
            },
        ),
    ]
