# Generated by Django 5.1.2 on 2025-06-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_client_id_alter_clientgroup_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='group',
        ),
        migrations.AddField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, в которые входит клиент', related_name='clients', to='booking.clientgroup', verbose_name='Группы клиента'),
        ),
    ]
