# Generated by Django 5.1.2 on 2024-10-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('hash', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('comment', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('idoblast', models.IntegerField()),
                ('phone', models.CharField(max_length=150)),
                ('howknow', models.IntegerField()),
                ('comment2', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
