# Generated by Django 5.1.2 on 2025-06-18 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_remove_client_group_client_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название помещения', max_length=150, unique=True, verbose_name='Название помещения')),
                ('description', models.TextField(blank=True, help_text='Описание помещения', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'db_table': 'areas',
            },
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterField(
            model_name='room',
            name='hourend',
            field=models.TimeField(help_text='Время окончания работы комнаты', verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hourstart',
            field=models.TimeField(help_text='Время начала работы комнаты', verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Наименование комнаты', max_length=150, unique=True, verbose_name='Наименование комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='reservation_type',
            field=models.ManyToManyField(help_text='Типы бронирования (сценарии), доступные для комнаты', related_name='rooms', to='booking.reservationtype', verbose_name='Типы бронирования (сценарии)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='service',
            field=models.ManyToManyField(help_text='Услуги доступные для комнаты', related_name='services', to='booking.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='room',
            name='area',
            field=models.ForeignKey(blank=True, help_text='ID помещения, к которому относится комната', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.area', verbose_name='Помещение'),
        ),
    ]
