# Generated by Django 5.1.2 on 2024-10-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('prior', models.IntegerField()),
                ('idgruppa', models.IntegerField()),
            ],
            options={
                'db_table': 'uslugi',
            },
        ),
    ]
