# Generated by Django 5.1.2 on 2024-10-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_uslugi'),
    ]

    operations = [
        migrations.CreateModel(
            name='UslugiBron',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idbron', models.IntegerField()),
                ('idusluga', models.IntegerField()),
                ('timehour', models.CharField(max_length=50)),
                ('skidka', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'uslugibron',
            },
        ),
    ]
