# Generated by Django 5.1.2 on 2026-01-02 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_specialist_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='specialist_service',
            field=models.ForeignKey(blank=True, help_text='Услуга преподавателя (для сценария Музыкальная школа)', null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.specialistservice', verbose_name='Услуга преподавателя'),
        ),
    ]
