# Generated by Django 5.1.2 on 2024-11-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_uslugibron'),
    ]

    operations = [
        migrations.AddField(
            model_name='bron',
            name='datetimeend',
            field=models.DateTimeField(help_text='Дата и время окончания брони', null=True),
        ),
        migrations.AddField(
            model_name='bron',
            name='datetimestart',
            field=models.DateTimeField(help_text='Дата и время начала брони', null=True),
        ),
    ]
