# Generated by Django 5.1.2 on 2024-11-14 11:53

from django.db import migrations, models
import datetime


def migrate_dates(apps, schema_editor):
    Bron = apps.get_model('booking', 'Bron')
    for bron in Bron.objects.all():
        bron.datetimestart = datetime.datetime.fromtimestamp(int(bron.timestart))
        bron.datetimeend = datetime.datetime.fromtimestamp(int(bron.timeend))
        bron.save()


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_bron_datetimeend_bron_datetimestart'),
    ]

    operations = [
        migrations.RunPython(migrate_dates),
    ]
