# Generated by Django 5.1.2 on 2024-11-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_migrate_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bron',
            name='day',
        ),
        migrations.RemoveField(
            model_name='bron',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='bron',
            name='timeend',
        ),
        migrations.RemoveField(
            model_name='bron',
            name='timestart',
        ),
        migrations.RemoveField(
            model_name='bron',
            name='year',
        ),
        migrations.AlterField(
            model_name='bron',
            name='datetimeend',
            field=models.DateTimeField(help_text='Дата и время окончания брони'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='datetimestart',
            field=models.DateTimeField(help_text='Дата и время начала брони'),
        ),
    ]
