# Generated by Django 5.1.2 on 2024-11-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_remove_bron_day_remove_bron_mon_remove_bron_timeend_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bron',
            new_name='Reservation',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservations',
        ),
    ]
