# Generated by Django 5.1.2 on 2024-11-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_rename_bron_reservation_alter_reservation_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hash',
        ),
    ]
