# Generated by Django 5.1.2 on 2024-11-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_remove_reservation_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='idprepod',
            new_name='specialist_id',
        ),
    ]
