# Generated by Django 5.1.2 on 2026-02-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_area_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='role',
            field=models.CharField(choices=[('teacher', 'Преподаватель'), ('sound_engineer', 'Звукорежиссёр'), ('technician', 'Техник')], default='teacher', help_text='Роль специалиста в системе', max_length=20, verbose_name='Роль'),
        ),
    ]
