# Generated by Django 5.1.2 on 2024-11-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='iduser',
            new_name='client_id',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='specialist_id',
            field=models.IntegerField(help_text='ID Специалиста, закрепленного за бронью', null=True),
        ),
    ]
