# Generated by Django 5.1.2 on 2024-11-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_rename_iduser_reservation_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client_id',
            field=models.IntegerField(help_text='ID Клиента, закрепленного за бронью'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='specialist_id',
            field=models.IntegerField(blank=True, help_text='ID Специалиста, закрепленного за бронью', null=True),
        ),
    ]
