# Generated by Django 5.1.2 on 2026-02-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_specialist_add_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='scenarios',
            field=models.ManyToManyField(blank=True, help_text='Сценарии, в которых участвует специалист', related_name='specialists', to='booking.scenario', verbose_name='Сценарии'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Преподаватель'), ('sound_engineer', 'Звукорежиссёр'), ('technician', 'Техник')], default='teacher', help_text='Роль специалиста в системе', max_length=20, verbose_name='Роль'),
        ),
    ]
