# Generated by Django 5.1.2 on 2026-02-09 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_specialist_add_admin_role_and_scenarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='client',
            field=models.ForeignKey(blank=True, help_text='ID клиента (для тех случаев, когда специалист выступает в роли клиента для бронирования)', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.client', verbose_name='ID клиента'),
        ),
    ]
