# Generated by Django 5.1.2 on 2024-11-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_alter_reservation_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client_group_id',
            field=models.IntegerField(blank=True, help_text='ID группы (коллектива) клиента, закрепленного за бронью, если групповое бронирование', null=True, verbose_name='ID группы клиента'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client_id',
            field=models.IntegerField(help_text='ID клиента, закрепленного за бронью', verbose_name='ID клиента'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetimeend',
            field=models.DateTimeField(help_text='Дата и время окончания брони', verbose_name='Datetime конца'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetimestart',
            field=models.DateTimeField(help_text='Дата и время начала брони', verbose_name='Datetime начала'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='specialist_id',
            field=models.IntegerField(blank=True, help_text='ID специалиста, закрепленного за бронью', null=True, verbose_name='ID специалиста'),
        ),
    ]
