# Generated by Django 5.1.2 on 2026-02-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_specialist_client_blank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialistweeklyinterval',
            options={'ordering': ('specialist', 'scenario', 'weekday', 'start_time'), 'verbose_name': 'Интервал работы специалиста (неделя)', 'verbose_name_plural': 'Интервалы работы специалистов (неделя)'},
        ),
        migrations.AlterUniqueTogether(
            name='specialistscheduleoverride',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='specialistscheduleoverride',
            name='scenario',
            field=models.ForeignKey(blank=True, help_text='Сценарий, к которому относится исключение (пусто = глобальное)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_schedule_overrides', to='booking.scenario', verbose_name='Сценарий'),
        ),
        migrations.AddField(
            model_name='specialistweeklyinterval',
            name='scenario',
            field=models.ForeignKey(blank=True, help_text='Сценарий, к которому относится интервал (пусто = глобальное расписание)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_weekly_intervals', to='booking.scenario', verbose_name='Сценарий'),
        ),
        migrations.AlterUniqueTogether(
            name='specialistscheduleoverride',
            unique_together={('specialist', 'date', 'scenario')},
        ),
    ]
