# Generated by Django 5.1.2 on 2024-11-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_reservation_client_group_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='idroom',
            new_name='room_id'
        )
    ]
