# Generated by Django 5.1.2 on 2024-11-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_remove_reservation_idroom_reservation_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_type_id',
            field=models.IntegerField(default=0, help_text='ID типа бронирования (шаблона направления)', verbose_name='ID типа брони'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_id',
            field=models.IntegerField(help_text='ID помещения, которое забронировано', verbose_name='ID помещения'),
        ),
    ]
