# Generated by Django 5.1.2 on 2024-11-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_reservation_reservation_type_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hide',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='numbron',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pay',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='period',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type_id',
            field=models.IntegerField(help_text='ID типа бронирования (шаблона направления)', verbose_name='ID типа брони'),
        ),
    ]
