# Generated by Django 5.1.2 on 2024-11-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_remove_reservation_hide_remove_reservation_numbron_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'CONFIRMED_UNPAID'), (2, 'CONFIRMED_PAID')], default=0, help_text='Статус брони (не подтверждена, подтверждена, оплачена)', verbose_name='Статус брони'),
        ),
    ]
