# Generated by Django 5.1.2 on 2024-11-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.TextField(help_text='Комментарий к брони', null=True, verbose_name='Комментарий'),
        ),
    ]
