# Generated by Django 5.1.2 on 2024-11-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_alter_reservation_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthTable',
        ),
    ]
