# Generated by Django 5.1.2 on 2024-11-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_delete_authtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveClient',
        ),
    ]
