# Generated by Django 5.1.2 on 2024-11-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0039_delete_activeclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Наименование типа бронирования (шаблона направления)', max_length=100, unique=True, verbose_name='Наименование типа бронирования')),
            ],
            options={
                'verbose_name': 'Тип бронирования (шаблон направления)',
                'verbose_name_plural': 'Типы бронирования (шаблоны направлений)',
                'db_table': 'reservation_types',
            },
        ),
    ]
