# Generated by Django 5.1.2 on 2024-11-20 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_reservationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type_id',
            field=models.ForeignKey(help_text='ID типа бронирования (шаблона направления)', on_delete=django.db.models.deletion.PROTECT, to='booking.reservationtype', verbose_name='ID типа брони'),
        ),
    ]
