# Generated by Django 5.1.2 on 2024-11-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_alter_reservation_reservation_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_type_id',
            new_name='reservation_type',
        ),
    ]
