# Generated by Django 5.1.2 on 2024-11-20 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_rename_reservation_type_id_reservation_reservation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ФИО специалиста', max_length=100, unique=True, verbose_name='ФИО специалиста')),
                ('active', models.BooleanField(default=True, help_text='Активность специалиста (работает или нет)', verbose_name='Активность специалиста')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
                'db_table': 'specialists',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Наименование услуги', max_length=100, unique=True, verbose_name='Наименование услуги')),
                ('active', models.BooleanField(default=True, help_text='Активность услуги (включена или нет)', verbose_name='Активность услуги')),
                ('reservation_type', models.ForeignKey(help_text='ID типа бронирования (шаблона направления)', on_delete=django.db.models.deletion.PROTECT, to='booking.reservationtype', verbose_name='ID типа брони')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='SpecialistServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Стоимость услуги', max_digits=10)),
                ('service', models.ForeignKey(help_text='ID услуги', on_delete=django.db.models.deletion.PROTECT, to='booking.service')),
                ('specialist', models.ForeignKey(help_text='ID специалиста', on_delete=django.db.models.deletion.PROTECT, to='booking.specialist')),
            ],
            options={
                'db_table': 'specialist_service_prices',
                'unique_together': {('specialist', 'service')},
            },
        ),
        migrations.AddField(
            model_name='specialist',
            name='services',
            field=models.ManyToManyField(help_text='Услуги, которые предоставляет специалист', through='booking.SpecialistServicePrice', to='booking.service'),
        ),
    ]
