# Generated by Django 5.1.2 on 2024-11-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_specialist_service_specialistserviceprice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
    ]
