# Generated by Django 5.1.2 on 2024-11-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0044_rename_user_client_alter_client_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='client',
            field=models.ForeignKey(help_text='ID клиента (для тех случаев, когда специалист выступает в роли клиента для бронирования', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.client', verbose_name='ID клиента'),
        ),
    ]
