# Generated by Django 5.1.2 on 2024-11-20 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0045_specialist_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='color',
        ),
        migrations.RemoveField(
            model_name='client',
            name='comment2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='client',
            name='howknow',
        ),
        migrations.RemoveField(
            model_name='client',
            name='idoblast',
        ),
        migrations.RemoveField(
            model_name='client',
            name='login',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='role',
        ),
        migrations.AlterField(
            model_name='specialist',
            name='client',
            field=models.ForeignKey(help_text='ID клиента (для тех случаев, когда специалист выступает в роли клиента для бронирования)', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.client', verbose_name='ID клиента'),
        ),
    ]
