# Generated by Django 5.1.2 on 2024-11-20 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_alter_client_options_remove_client_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название группы', max_length=100, unique=True, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа клиента',
                'verbose_name_plural': 'Группы клиентов',
                'db_table': 'client_groups',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='group',
            field=models.ForeignKey(help_text='ID группы клиента', null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.clientgroup'),
        ),
    ]
