# Generated by Django 5.1.2 on 2024-11-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0047_clientgroup_client_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='name',
        ),
    ]
