# Generated by Django 5.1.2 on 2024-11-20 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0048_rename_email_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий к клиенту', null=True, verbose_name='Комментарий к клиенту'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='ФИО клиента', max_length=150, verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text='Телефон клиента', max_length=150, null=True, verbose_name='Телефон клиента'),
        ),
        migrations.CreateModel(
            name='ClientRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Оценка выставленная клиенту')),
                ('comment', models.TextField(blank=True, help_text='Комментарий к оценке', null=True, verbose_name='Комментарий к оценке')),
                ('client', models.ForeignKey(help_text='ID клиента', on_delete=django.db.models.deletion.PROTECT, to='booking.client')),
            ],
            options={
                'verbose_name': 'Оценка клиента',
                'verbose_name_plural': 'Оценки клиентов',
                'db_table': 'client_ratings',
            },
        ),
    ]
