# Generated by Django 5.1.2 on 2024-11-20 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_alter_client_comment_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client_group_id',
            field=models.ForeignKey(help_text='ID группы (коллектива) клиента, закрепленного за бронью, если групповое бронирование', null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.clientgroup', verbose_name='ID группы клиента'),
        ),
    ]
