# Generated by Django 5.1.2 on 2024-11-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_rename_client_group_id_reservation_client_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='specialist_id',
            field=models.ForeignKey(help_text='ID специалиста, закрепленного за бронью', null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.specialist', verbose_name='ID специалиста'),
        ),
    ]
