# Generated by Django 5.1.2 on 2024-11-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0052_alter_reservation_specialist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='specialist_id',
            new_name='specialist',
        ),
    ]
