# Generated by Django 5.1.2 on 2024-11-20 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0053_rename_specialist_id_reservation_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client_id',
            field=models.ForeignKey(help_text='ID клиента, закрепленного за бронью', on_delete=django.db.models.deletion.PROTECT, to='booking.client', verbose_name='ID клиента'),
        ),
    ]
