# Generated by Django 5.1.2 on 2024-11-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0054_alter_reservation_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='client_id',
            new_name='client',
        ),
    ]
