# Generated by Django 5.1.2 on 2024-11-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0055_rename_client_id_reservation_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
    ]
