# Generated by Django 5.1.2 on 2024-11-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0056_alter_room_options_alter_room_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Помещение', 'verbose_name_plural': 'Помещения'},
        ),
    ]
