# Generated by Django 5.1.2 on 2024-11-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0057_alter_room_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='idoblast',
        ),
        migrations.RemoveField(
            model_name='room',
            name='period',
        ),
        migrations.RemoveField(
            model_name='room',
            name='prior',
        ),
    ]
