# Generated by Django 5.1.2 on 2024-11-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0058_remove_room_idoblast_remove_room_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hourend',
            field=models.TimeField(help_text='Время окончания работы помещения', verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hourstart',
            field=models.TimeField(help_text='Время начала работы помещения', verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Наименование помещения', max_length=150, unique=True, verbose_name='Наименование помещения'),
        ),
    ]
