# Generated by Django 5.1.2 on 2024-11-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0059_alter_room_hourend_alter_room_hourstart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reservation_type',
            field=models.ManyToManyField(help_text='Виды бронирования, доступные для помещения', related_name='rooms', to='booking.reservationtype'),
        ),
    ]
