# Generated by Django 5.1.2 on 2024-11-20 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0060_room_reservation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_id',
            field=models.ForeignKey(help_text='ID помещения, которое забронировано', on_delete=django.db.models.deletion.PROTECT, to='booking.room', verbose_name='ID помещения'),
        ),
        migrations.AlterField(
            model_name='room',
            name='reservation_type',
            field=models.ManyToManyField(help_text='Типы бронирования, доступные для помещения', related_name='rooms', to='booking.reservationtype'),
        ),
    ]
