# Generated by Django 5.1.2 on 2024-11-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0061_alter_reservation_room_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room_id',
            new_name='room',
        ),
    ]
