# Generated by Django 5.1.2 on 2024-11-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0062_rename_room_id_reservation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='reservation_type',
            field=models.ManyToManyField(help_text='Типы бронирования доступные для специалиста', related_name='reservation_types', to='booking.reservationtype'),
        ),
    ]
