# Generated by Django 5.1.2 on 2024-11-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0063_specialist_reservation_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColoredBlock',
        ),
    ]
