# Generated by Django 5.1.2 on 2024-11-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0064_delete_coloredblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectUser',
        ),
    ]
