# Generated by Django 5.1.2 on 2024-11-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0065_delete_connectuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gruslugi',
        ),
    ]
