# Generated by Django 5.1.2 on 2024-11-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0066_delete_gruslugi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
