# Generated by Django 5.1.2 on 2024-11-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0067_delete_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='services',
        ),
    ]
