# Generated by Django 5.1.2 on 2024-11-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0068_remove_specialist_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='services',
            field=models.ManyToManyField(help_text='Услуги, которые предоставляет специалист', related_name='services', to='booking.service'),
        ),
    ]
