# Generated by Django 5.1.2 on 2024-11-23 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0070_remove_specialist_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_reservation_time', models.TimeField(help_text='Минимальное время бронирования (размер тарифной единицы)')),
                ('tariff_unit_cost', models.DecimalField(decimal_places=2, help_text='Стоимость тарифной единицы', max_digits=10)),
                ('reservation_type', models.ForeignKey(help_text='ID типа бронирования (сценария)', on_delete=django.db.models.deletion.PROTECT, to='booking.reservationtype')),
            ],
        ),
    ]
