# Generated by Django 5.1.2 on 2024-11-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0071_tariffunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialistServicePrice',
        ),
    ]
