# Generated by Django 5.1.2 on 2024-11-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0072_delete_specialistserviceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='service',
            field=models.ManyToManyField(help_text='Услуги доступные для помещения', related_name='services', to='booking.service'),
        ),
    ]
