# Generated by Django 5.1.2 on 2024-11-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0073_room_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariffunit',
            options={'verbose_name': 'Тарифная единица', 'verbose_name_plural': 'Тарифные единицы'},
        ),
        migrations.AlterModelTable(
            name='tariffunit',
            table='tariff_units',
        ),
    ]
