# Generated by Django 5.1.2 on 2024-11-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0074_alter_tariffunit_options_alter_tariffunit_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerSmena',
        ),
    ]
