# Generated by Django 5.1.2 on 2024-11-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0075_delete_managersmena'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oblast',
        ),
    ]
