# Generated by Django 5.1.2 on 2024-11-24 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0076_delete_oblast'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Наименование группы услуг', max_length=100, unique=True, verbose_name='Наименование группы услуг')),
                ('active', models.BooleanField(default=True, help_text='Активность группы услуг (включена или нет)', verbose_name='Активность группы услуг')),
            ],
            options={
                'verbose_name': 'Группа услуг',
                'verbose_name_plural': 'Группы услуг',
                'db_table': 'service_groups',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(help_text='Баланс тарифных единиц')),
                ('client', models.ForeignKey(help_text='ID клиента', on_delete=django.db.models.deletion.PROTECT, to='booking.client')),
                ('reservation_type', models.ForeignKey(help_text='ID сценария', on_delete=django.db.models.deletion.PROTECT, to='booking.reservationtype')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'db_table': 'subscriptions',
            },
        ),
        migrations.DeleteModel(
            name='Abon',
        ),
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Группа услуг', null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.servicegroup', verbose_name='Группа услуг'),
        ),
    ]
