# Generated by Django 5.1.2 on 2024-11-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0077_servicegroup_subscription_delete_abon_service_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='reservation_type',
        ),
        migrations.AddField(
            model_name='service',
            name='reservation_type',
            field=models.ManyToManyField(help_text='Типы бронирования для услуги', related_name='services', to='booking.reservationtype', verbose_name='Типы бронирования'),
        ),
    ]
