# Generated by Django 5.1.2 on 2024-11-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0078_remove_service_reservation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Услуги, включенные в бронь', related_name='reservations', to='booking.service', verbose_name='Услуги'),
        ),
    ]
