# Generated by Django 5.1.2 on 2024-11-27 16:50

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def create_initial_statuses(apps, schema_editor):
    ReservationStatusType = apps.get_model('booking', 'ReservationStatusType')
    
    # Создаем начальные статусы
    statuses = [
        {
            'name': 'Не подтверждена',
            'description': 'Бронь создана, но еще не подтверждена'
        },
        {
            'name': 'Подтверждена, не оплачена',
            'description': 'Бронь подтверждена, но еще не оплачена'
        },
        {
            'name': 'Подтверждена и оплачена',
            'description': 'Бронь подтверждена и оплачена'
        }
    ]
    
    for status_data in statuses:
        ReservationStatusType.objects.create(**status_data)


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0079_reservation_services'),
    ]

    operations = [
        # Создаем новую модель ReservationStatusType
        migrations.CreateModel(
            name='ReservationStatusType',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('name', models.CharField(help_text='Название статуса', max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание статуса', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип статуса бронирования',
                'verbose_name_plural': 'Типы статусов бронирования',
                'db_table': 'reservation_status_types',
            },
        ),
        
        # Создаем начальные статусы
        migrations.RunPython(create_initial_statuses),
        
        # Добавляем поля created_at и updated_at в Reservation
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, help_text='Дата создания брони', verbose_name='Создана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now, help_text='Дата обновления брони', verbose_name='Обновлена'),
            preserve_default=False,
        ),
        
        # Создаем новое поле status_new как ForeignKey
        migrations.AddField(
            model_name='reservation',
            name='status_new',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='booking.reservationstatustype',
                help_text='Статус брони',
                verbose_name='Статус',
                null=True
            ),
        ),
        
        # Удаляем старое поле status
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        
        # Переименовываем status_new в status
        migrations.RenameField(
            model_name='reservation',
            old_name='status_new',
            new_name='status',
        ),
    ]
